source 'http://rubygems.org'

gem 'mysql'
gem 'rails', '~> 2.3'
gem 'geminstaller', '0.5.4'
gem 'paperclip', '~> 2.2.9.2'
gem 'state_machine', '~> 0.7.3'
gem 'rubaidh-rails_sql_views', '~> 0.7.1'
gem 'haml', '~> 2.0.9'
gem 'rmagick', '~> 2.11.0'
gem 'sanitize_email', :git => 'https://github.com/jtrupiano/sanitize_email.git'
