---
defaults:
  install_options: --no-ri --no-rdoc
gems:
- name: rails
  version: '= 2.3.2'
- name: state_machine
  version: '~> 0.7.3'
- name: rails_sql_views
  version: '~> 0.7.0'
- name: haml
  version: '~> 2.0.9'